### ISSUE TITLE
Build/run instructions are incomplete.

### ISSUE THREAD

**Issue by almereyda** [jagger27/iwikii#3]
I'm happy to find a Go wiki that is not just a demonstrator from a tutorial. When trying out all there is in https://github.com/topics/wiki/ I can assure there is a lot of non-working pieces of software.

Unfortunately the build, run instructions are a little incomplete.

First it seems `sass` is not an optional dependency, at least for `make` which I tried. Linking to http://sass-lang.com/install could help here.

Second there are no instructions on how to set up a `config.yml` for the application, why starting it will fail with:

```
./iwikii
panic: open config.yaml: no such file or directory

goroutine 1 [running]:
main.SetupConfig(0x0)
	/home/yala/go/src/github.com/jagger27/iwikii/config.go:25 +0x61f
main.Setup(0x9)
	/home/yala/go/src/github.com/jagger27/iwikii/setup.go:13 +0x37
main.main()
	/home/yala/go/src/github.com/jagger27/iwikii/server.go:30 +0x37
```

Thank you for writing a new wiki engine and good luck in the long run!

**Comment by jagger27** [comment]
Better late than never :3

**Comment by almereyda** [comment]
👏🏽  hehe
